### ISSUE TITLE
Dynamic list of contributor avatars on lorikeet.design

### ISSUE THREAD

**Issue by jounih** [lorikeetui/website#4]
Right now we have a static png of the avatars of contributors - would be nice if this was dynamically generated so we don't need to maintain it.

<img width="1290" alt="screenshot 2018-11-05 at 16 57 07" src="https://user-images.githubusercontent.com/10109867/48013280-d93fbe00-e11b-11e8-89a1-a1bf4403edcb.png">

Github has some APIs that would probably enable this - with this one we get list of all the contributors and the url to their avatar image - https://developer.github.com/v3/repos/#list-contributors

We could grab the avatar image of each contributor with that and do border-radius:50% for each to show them as circles.

**Comment by sohkai** [comment]
Potentially this is something we could automate with https://github.com/jfmengels/all-contributors-cli, but I'm not sure if it's worth it to get real-time updates of contributors vs. rebuilding the site after releases.

**Comment by jounih** [comment]
We could use an existing lib if it helps, but would need to modify it anyway to look like the above. The vanilla GitHub API for this looks super simple..  looks like it's one call to grab all the contributor names/gravatar urls.

`GET /repos/:owner/:repo/contributors`

**Comment by jounih** [comment]
@delfipolito can you please reassign this one to Ariel if you want to focus on the docs?
